# Generated by Django 3.2.7 on 2021-09-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsal', '0016_auto_20210905_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='character',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='scene',
        ),
        migrations.RemoveField(
            model_name='atndchangelog',
            name='production',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='rehearsal',
        ),
        migrations.RemoveField(
            model_name='character',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='character',
            name='production',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='production',
        ),
        migrations.RemoveField(
            model_name='place',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='production',
        ),
        migrations.RemoveField(
            model_name='scncomment',
            name='mod_prod_user',
        ),
        migrations.RemoveField(
            model_name='scncomment',
            name='scene',
        ),
        migrations.RemoveField(
            model_name='rehearsal',
            name='place',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Appearance',
        ),
        migrations.DeleteModel(
            name='AtndChangeLog',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Scene',
        ),
        migrations.DeleteModel(
            name='ScnComment',
        ),
    ]
