# Generated by Django 3.2.7 on 2021-09-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsal', '0019_auto_20210909_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehearsal',
            name='prog',
            field=models.CharField(choices=[(' ', ' '), ('DONE!!!', 'DONE!!!'), ('Started', 'Started')], default='0', max_length=10),
        ),
    ]
