# Generated by Django 3.2.7 on 2021-09-09 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0008_auto_20210909_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['exp_dt'], 'verbose_name': 'PLOJECTへの招待', 'verbose_name_plural': 'PLOJECTへの招待'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name': 'PLOJECT', 'verbose_name_plural': 'PLOJECT'},
        ),
        migrations.AlterModelOptions(
            name='produser',
            options={'verbose_name': 'STAFF', 'verbose_name_plural': 'STAFF'},
        ),
        migrations.AlterField(
            model_name='invitation',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.production', verbose_name='PLOJECT'),
        ),
        migrations.AlterField(
            model_name='production',
            name='name',
            field=models.CharField(max_length=50, verbose_name='PLOJECT'),
        ),
        migrations.AlterField(
            model_name='produser',
            name='is_editor',
            field=models.BooleanField(default=False, verbose_name='EDITER'),
        ),
        migrations.AlterField(
            model_name='produser',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='OWNER'),
        ),
        migrations.AlterField(
            model_name='produser',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.production', verbose_name='PLOJECT'),
        ),
        migrations.AlterField(
            model_name='produser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='STAFF'),
        ),
    ]
