# Generated by Django 3.2.7 on 2021-09-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_auto_20210909_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['exp_dt'], 'verbose_name': 'PROJECTへの招待', 'verbose_name_plural': 'PROJECTへの招待'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name': 'PROJECT', 'verbose_name_plural': 'PROJECT'},
        ),
        migrations.AlterField(
            model_name='invitation',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.production', verbose_name='PROJECT'),
        ),
        migrations.AlterField(
            model_name='production',
            name='name',
            field=models.CharField(max_length=50, verbose_name='PROJECT'),
        ),
        migrations.AlterField(
            model_name='produser',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.production', verbose_name='PROJECT'),
        ),
    ]
